image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp index.html .public/
    - cp style.css .public/
    - cp -r images .public/
  artifacts:
    paths:
      - .public
  rules:
    - if: $CI_COMMIT_BRANCH
